void* reg_gpr[100];
void* reg_arith;
void* data_ptr;
void* data_lim;
int main() {
goto start;
split_k1: ;
reg_gpr[0] = reg_gpr[1];
goto k1;
k1: ;
goto k0;
k0: ;
return 0;
start: ;
reg_gpr[0] = malloc(sizeof(void*)*1);
((void**)(reg_gpr[0]))[0] = &&split_k1;
reg_gpr[2] = reg_gpr[0];
reg_gpr[1] = 0;
goto Comb_main;
Comb_split_k10: ;
reg_gpr[0] = ((void**)(reg_gpr[2]))[1];
goto Comb_k10;
Comb_k10: ;
goto Comb_k8;
Comb_k8: ;
reg_gpr[2] = ((void**)(reg_gpr[0]))[0];
reg_gpr[3] = malloc(sizeof(void*)*1);
((void**)(reg_gpr[3]))[0] = reg_gpr[1];
reg_gpr[1] = reg_gpr[3];
reg_arith = reg_gpr[2];
reg_gpr[2] = reg_gpr[0];
reg_gpr[0] = reg_arith;
reg_arith = reg_gpr[0];
goto *reg_arith;
Comb_main: ;
reg_gpr[0] = malloc(sizeof(void*)*2);
((void**)(reg_gpr[0]))[0] = &&Comb_split_k10;
((void**)(reg_gpr[0]))[1] = reg_gpr[2];
reg_gpr[1] = 3;
goto Comb_f12;
Comb_f12: ;
reg_gpr[2] = ((void**)(reg_gpr[0]))[0];
reg_gpr[3] = malloc(sizeof(void*)*2);
((void**)(reg_gpr[3]))[0] = 0;
((void**)(reg_gpr[3]))[1] = reg_gpr[1];
reg_gpr[1] = reg_gpr[3];
reg_arith = reg_gpr[2];
reg_gpr[2] = reg_gpr[0];
reg_gpr[0] = reg_arith;
reg_arith = reg_gpr[0];
goto *reg_arith;
}
